services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - '3306'
  postgres:
    image: 'postgres:latest'
    container_name: postgres_todolist
    environment:
      - POSTGRES_DB=todo_list_db
      - POSTGRES_USER=todo_admin
      - POSTGRES_PASSWORD=todo_password
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - todolist:/var/lib/postgresql/data
#  sqlserver:
#    image: 'mcr.microsoft.com/mssql/server:latest'
#    environment:
#      - 'ACCEPT_EULA=yes'
#      - 'MSSQL_PID=express'
#      - 'MSSQL_SA_PASSWORD=verYs3cret'
#    ports:
#      - '1433'


volumes:
  todolist: